### ISSUE TITLE
来逛一逛大神的github

### ISSUE THREAD

**Issue by Mrdouhua** [gaoxianglyx/redux-notes#1]
上次那个给react-router组件传属性会传了吗？

**Comment by gaoxianglyx** [comment]
@Mrdouhua 哈哈又开我玩笑，就是用redux就能解决，但是我没有写，感觉有点复杂，先看其他的了。这两天在追剧哈哈，小兵在学redux了吗？

**Comment by Mrdouhua** [comment]
没有啊，这两天东搞搞系搞搞。想投个简历耍耍，你们投了没有。

**Comment by gaoxianglyx** [comment]
@Mrdouhua 我没有投，我都还没有做自己的简历，你打算找实习了？我打算年后再做简历，这里应该要看哈书了

**Comment by Mrdouhua** [comment]
我先试下水，书还是要看的，今天刚到了一本书，买了一本js算法的，不是那本动物书，是另外一本。

**Comment by gaoxianglyx** [comment]
我感觉我基础好多都忘了，而且掌握得不系统，必须要好好复习了，你寒假准备多少号回学校?

**Comment by Mrdouhua** [comment]
初7初8吧，但是还不是很确定。
